### ISSUE TITLE
🎨 Hey

### ISSUE THREAD

**Issue by cdloh** [jloh/referrer-spam-blacklist#3]
<redacted>

**Comment by cdloh** [comment]
█▄༼ຈل͜ຈ༽▄█ yeah i work out

**Comment by cdloh** [comment]
(̿▀̿ ̿Ĺ̯̿̿▀̿ ̿)̄ IM DONG,JAMES DONG (̿▀̿ ̿Ĺ̯̿̿▀̿ ̿)̄

**Comment by cdloh** [comment]
༼ ▀̿Ĺ̯▀̿ ̿ ༽Hello, my name is Juan Pastoroni, CEO of Copy Pasta Industries. I'd like to let you know that we've just gained copyrights on a lot of copy pastas seen in this chat. If you are using them right now, please refrain from doing so, or risk being fined under copyright infringement. Thank you, and don't be funny and copy and paste this. This is business, kid.༼ ▀̿Ĺ̯▀̿ ̿ ༽

**Comment by jloh** [comment]
adgagadg

**Comment by jloh** [comment]
adgadg

**Comment by jloh** [comment]
pizza
